#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(APPLICATIONPATIENTLISTFRAMEVIEWMODEL_LIB)
#  define APPLICATIONPATIENTLISTFRAMEVIEWMODEL_EXPORT Q_DECL_EXPORT
# else
#  define APPLICATIONPATIENTLISTFRAMEVIEWMODEL_EXPORT Q_DECL_IMPORT
# endif
#else
# define APPLICATIONPATIENTLISTFRAMEVIEWMODEL_EXPORT
#endif
